import Image from "next/image";

export function Disclaimer() {
  return (
    <section className="py-14">
      <div className="container mx-auto px-4 lg:px-8 max-w-4xl">
        <div className="glass-panel rounded-3xl p-8 md:p-10">
          <div className="flex items-center gap-3 mb-6">
            <Image src="/logo.png?v=2" alt="Softtooles Logo" width={150} height={150} />
            <h1 className="text-3xl font-bold">Disclaimer</h1>
          </div>

          <p className="text-sm text-muted-foreground mb-6">Last updated: March 22, 2026</p>

          <p className="text-muted-foreground leading-7 mb-4">
            The information, tools, and utilities available on Softtooles are provided for
            general informational and productivity purposes only. We work to keep outputs
            accurate and useful, but we do not guarantee that every result will be complete,
            error-free, or suitable for all technical and legal use cases.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-3">No Professional Advice</h2>
          <p className="text-muted-foreground leading-7 mb-4">
            Content and outputs generated by this website do not constitute legal, financial,
            tax, security, compliance, or professional engineering advice. You should consult
            a qualified professional before making critical decisions based on any output.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-3">Tool Output Responsibility</h2>
          <p className="text-muted-foreground leading-7 mb-4">
            By using Softtooles, you acknowledge that you are solely responsible for verifying
            tool results before using them in production systems, contracts, reports,
            security-sensitive workflows, or official documentation.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-3">Third-Party Content and Links</h2>
          <p className="text-muted-foreground leading-7 mb-4">
            Our website may include references to third-party services, libraries, or links.
            We do not control and are not responsible for external websites, their availability,
            security practices, or their content.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-3">Limitation of Liability</h2>
          <p className="text-muted-foreground leading-7 mb-4">
            To the maximum extent permitted by law, Softtooles and its team will not be liable
            for any direct, indirect, incidental, special, or consequential damages arising from
            your use of or inability to use the tools, including but not limited to data loss,
            business interruption, or workflow delays.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-3">Changes to This Disclaimer</h2>
          <p className="text-muted-foreground leading-7">
            We may revise this Disclaimer from time to time. Continued use of the website after
            updates means you accept the revised version.
          </p>
        </div>
      </div>
    </section>
  );
}
